Add configuration that requires login for poll creation
fsinfuhh/Bitpoll pull request #152
Opened 2023-12-15 15:20 UTC by timonegk

2023-12-15 15:45 UTC, Akasch requested changes
The rights are not checked if the POST is send manually as far as i can see

2023-12-15 15:45 UTC, Akasch commented on bitpoll/base/templates/base/index.html
> +                <p class="lead">{% blocktrans %}This instance is reserved for users of <a href="https://mafiasi.de">mafiasi.de</a>.
The url should be coming from config

2023-12-15 16:02 UTC, Akasch requested changes

2023-12-15 16:02 UTC, Akasch commented on bitpoll/base/views.py
> +    if request.method == 'POST' and request.user.is_authenticated:
This will always require a login, even if not required in the settings:

`if request.method == 'POST' and (request.user.is_authenticated or not settings.POLL_CREATION_REQUIRES_LOGIN)`

2024-01-12 16:35 UTC, ftsell approved these changes

2024-01-12 16:35 UTC, ftsell commented on bitpoll/base/templates/base/index.html
> +                <p class="lead">{% blocktrans %}This instance is reserved for users of <a href="{{ account_website }}">{{ account_name }}</a>.
Maybe you want to use `{% blocktrans trimmed %}` to reduce formatting related clutter in the translation files.

2024-01-12 17:00 UTC, merged