dockerize application (resolve #67)
fsinfuhh/Bitpoll pull request #68
Opened 2020-10-15 13:41 UTC by muety

2020-10-18 10:29 UTC, ftsell commented
thanks for the contribution :)

we have a Dockerfile in another repo (which is there because it grew out of historical reasons).
I'll compare it with the one you want to contribute sometime this week,

2020-10-21 09:30 UTC, ftsell requested changes
Once again; thank you for your contribution!

I do have some remarks which I would like you to address before this can get merged.
In case you are interested in the current deployments Dockerfile as reference it is located in [fsinfuhh/dockerfiles](https://github.com/fsinfuhh/dockerfiles/tree/master/bitpoll) but it's a bit old and I like your solution better :)

In general, I would also like @Akasch to at least have a look since Bitpoll is sort of his thing.

2020-10-21 09:30 UTC, ftsell commented on Dockerfile
> +WORKDIR app
We usually put our sources into `/app/src/` with other relevant directories then living in `/app/…` for example `/app/data/`

2020-10-21 09:30 UTC, ftsell commented on bitpoll/urls.py
> +    ]
If we want to serve staticfiles in production via Django, we should probably use a dedicated solution like [WhiteNoise](http://whitenoise.evans.io/en/stable/index.html).

@Akasch @wichmannpas what do you think?

2020-10-21 09:30 UTC, ftsell commented on bitpoll/settings_local.docker.py
> +    PIPELINE_ENABLED = True
These settings support static file pipelining but the relevant dependencies are not installed in the Dockerfile.

As I can see it, we require the packages [cssmin](https://www.npmjs.com/package/cssmin) and [uglify-js](https://www.npmjs.com/package/uglify-js).

2020-10-21 09:30 UTC, ftsell commented on entrypoint.sh
> +./manage.py migrate
I would also like to have a `./manage.py check --deploy` invocation

2020-10-22 20:25 UTC, muety commented on bitpoll/urls.py
> +    ]
I'm not particularly a Django expert. What are the benefits?

2020-10-22 21:32 UTC, muety commented on bitpoll/settings_local.docker.py
> +    PIPELINE_ENABLED = True
I removed these options as the feature doesn't seem to be implemented anyway (https://github.com/fsinfuhh/Bitpoll/blob/master/bitpoll/settings.py#L202).

2020-10-23 15:03 UTC, ftsell commented on bitpoll/settings_local.docker.py
> +    PIPELINE_ENABLED = True
fair point

2020-10-23 15:08 UTC, ftsell commented on bitpoll/urls.py
> +    ]
The benefits are that djangos internal staticfile serving was only ever meant for a development context (see the note [here under *Serving the files*](https://docs.djangoproject.com/en/3.0/howto/static-files/).

I think the classical approach is to have a webserver who serves these files and proxies through to the django application when necessary. This is also the way I would normally go.
That being said it is also possible to host static files from django directly even in production and WhiteNoise aims to exactly this. It implements additional things like setting proper cache options and serving the files as efficiently as possible.

I don't know if it can do media files though. @Akasch do we even use media files in Bitpoll?

2021-04-22 08:02 UTC, closed without merging